version: '3'

services:
  backend-match:
    build:
      context: ./match_api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  backend-user:
    build:
      context: ./user_api
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./view
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
